Update git submodules
* Update external/googletest from branch 'master'
  to b21299dc7da666f805e9a548f691a06bfbb32676
  - Upgrade googletest to 306f3754a71d6d1ac644681d3544d06744914228
    
    Test: None
    Change-Id: I54da767093147d6c8a2754ac1271e9e30d3bd7e0
    
  - Googletest export
    
    Explicitly default copy constructor in BoundSecondMatcher
    
    Since C++11, implicit defaulting of copy constructors is deprecated for types
    with user-defined copy assignment operators, so we should explicitly default the
    copy constructor of BoundSecondMatcher.
    
    PiperOrigin-RevId: 287587847
    
  - Merge pull request #2632 from Kravlalala:cmake/mingw_msys_build
    
    PiperOrigin-RevId: 287587126
    
  - Googletest export
    
    Add missing period.
    
    PiperOrigin-RevId: 287553550
    
  - Googletest export
    
    Fix typo in example.
    
    PiperOrigin-RevId: 287212448
    
  - Merge pull request #2639 from trzecieu:trzeci/move_ctor_assign
    
    PiperOrigin-RevId: 286896167
    
  - Googletest export
    
    Add option (default to disabled) to make C++ type parameterized tests (TYPED_TEST_P) fail when they're not instantiated.
    
    When an un-instantiated TYPED_TEST_P is found, a new test will be inserted that emits a suitable message. For now, that is just a notice, but the hope it to flip the bit to make it fail by default.
    
    PiperOrigin-RevId: 286408038
    
  - Merge pull request #2624 from ShabbyX:master
    
    PiperOrigin-RevId: 286397298
    
  - Googletest export
    
    Use C++11 variadic templates for InvokeArgumentAdl in gmock-generated-actions.h.
    
    Make InvokeArgumentAdl use variadic templates to generate its overloads instead
    of using pump.py syntax.
    
    PiperOrigin-RevId: 286267615
    
  - Googletest export
    
    Use C++11 variadic templates for InvokeArgumentAdl in gmock-generated-actions.h.
    
    Make InvokeArgumentAdl use variadic templates to generate its overloads instead
    of using pump.py syntax.
    
    PiperOrigin-RevId: 286148805
    
  - Make move operation noexcept.
  - Define default destructor for test classes
  - Deleted functions as part of public interface
  - Review notes: Return T& from assignment operators
  - Disable move constructor and assignment operator for test classes.
    
    Disable move operations for TEST() and TEST_F() macros.
    Previous implementation disabled only copy ctor and assing operator, but
    this was violating rule of 5[1], which was captured by static code analysis tools
    like clang-tidy `cppcoreguidelines-special-member-functions`.
    
    [1]: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c21-if-you-define-or-delete-any-default-operation-define-or-delete-them-all
    
  - Merge pull request #2590 from kuzkry:remove-workaround_g++-stale-comments
    
    PiperOrigin-RevId: 285812343
    
  - Googletest export
    
    Don't use fully qualified ::std types in code examples.
    
    Having a nested user-defined 'std' namespace anywhere in a program is a minefield and shouldn't be either explicitly supported or implicitly condoned.
    
    PiperOrigin-RevId: 285790182
    
  - Revert "Googletest export": disallow empty prefix
    
    This reverts commit 20b5b8ecc7a81d23b4716e22a2b35fd53379c8c6.
    Reason for revert: Breaks existing applications, such as ANGLE
    (angleproject.org), requires adding an extra prefix that needs to be
    typed for no reason (when testing from command line) and increases the
    logs' sizes by a non-trivial amount due to the very large number of
    tests ANGLE runs.
    
    Original commit message:
    
        Add a compile time check to ensure that the parameters to TEST_P and
        INSTANTIATE_TEST_SUITE_P are not empty. Some compilers already fail
        in that case and, even where it works, it's likely to result in
        technically invalid code by virtue of creating reserved identifiers:
        https://en.cppreference.com/w/cpp/language/identifiers
    
    First, every project is perfectly capable of adding a prefix if they
    want to support such a compiler. This change penalizes every
    project.
    
    Second, using a prefix such as `_p` also results in reserved
    identifiers, so this change is not really solving the problem.  For that
    matter, instead of generating `gtest_##prefix##...`, you can generate
    `gtest_x##prefix##...` to correctly fix the issue, including when empty
    prefixes are used.
    
  - Revert "Googletest export": Remove test for empty prefix
    
    This reverts commit 4c25e2b87fcb78abcfdee2739db9ed7a19754cd3.
    Reason for revert: Reverting the commit that disallows empty prefixes.
    
    Original commit message:
    
        Remove a test case rendered obsolete by disallowing empty argument for INSTANTIATE_TEST_SUITE_P.
        Remove the code that it was testing.
    
  - Workaround VS bug w.r.t empty arguments to macros
    
    Empty arguments can be passed to macros per C99 and C++11 specs, which
    can then be forwarded to other macros.
    
    Visual Studio's compiler has a bug in the following situation:
    
        #define A(x) #x
        #define B(x, y) A(x)
        B(, b)
    
    In the above case, Visual Studio first expands x to nothing, then
    complains that A is not invoked with the right amount of arguments.
    However, x in A(x) is still one argument, even if it expands to no
    preprocessing tokens.  See also https://stackoverflow.com/a/7674214.
    
  - Merge pull request #2589 from kuzkry:remove-workaround_g++-no-space-after-first-macro-argument
    
    PiperOrigin-RevId: 285255373
    
  - Googletest export
    
    Add GTEST_API_ to correct a build failure under MSCV.
    
    PiperOrigin-RevId: 285208464
    
  - Googletest export
    
    Use C++11 variadic templates for ActionHelper in gmock-generated-actions.h.
    
    Make ActionHelper use variadic templates to generate Perform static member function specializations instead of using pump.py syntax.
    
    PiperOrigin-RevId: 284988441
    
  - Googletest export
    
    Detect when C++ parametric tests (TEST_P) are not instantiated.
    
    When an un-instantiated TEST_P is found, a new test will be inserted that will emit a warning message.
    
    This can be made to error with minor code edits.
    In the future, that is intended to be the default.
    
    PiperOrigin-RevId: 284901666
    
  - Merge pull request #2595 from kuzkry:remove-workaround_msvc-warning-4355
    
    PiperOrigin-RevId: 284234675
    
  - Merge pull request #2592 from kuzkry:remove-workaround_msvc-error-C2665
    
    PiperOrigin-RevId: 284207090
    
  - Googletest export
    
    Require all appveyor googletest windows builds to work on Pull Requests to increase CI coverage
    
    PiperOrigin-RevId: 284206759
    
  - Activate GNU extensions in case of MSYS generator
    
  - remove MSVC workaround: warning 4355
    
  - remove MSVC workaround: error C2665
    
  - remove stale comments about older GCC versions
    
  - remove g++ 2.95.0 workaround: no space after first comma in macros