Update git submodules
* Update external/googletest from branch 'master'
  to a09ca9ae1c2ef1b305235d905bcd8444f9a8ce44
  - Upgrade googletest to 78fdd6c00b8fa5dd67066fbb796affc87ba0e075
    
    Test: None
    Change-Id: I30c7666da39341e4c0babba375b46791836127da
    
  - Merge pull request #2609 from kuzkry:revert-2596
    
    PiperOrigin-RevId: 284041013
    
  - Googletest export
    
    Change googletest to notice failures during SetUpTestSuite() and TearDownTestSuite().
    
    Previously, errors that occurred during those functions were logged but otherwise ignored. After this change, such failures will cause the test to fail and a brief summary will be printed at the bottom of the test log.
    
    See https://github.com/google/googletest/issues/2330.
    
    PiperOrigin-RevId: 284033342
    
  - Googletest export
    
    Update example Environment class destructor annotation
    
    PiperOrigin-RevId: 283986183
    
  - Merge pull request #2594 from kuzkry:remove-workaround_msvc-unneeded-const-dropping
    
    PiperOrigin-RevId: 283979494
    
  - Googletest export
    
    Internal change
    
    PiperOrigin-RevId: 283948137
    
  - Googletest export
    
    Clarify use of IsTrue and IsFalse matchers.
    
    These matchers are subtle and confusing: what are they for?
    The docs in the code are clear, but not very accessible.
    googletest/googlemock/include/gmock/gmock-more-matchers.h
    
    PiperOrigin-RevId: 283393275
    
  - Merge pull request #2603 from maximilianschwab:patch-1
    
    PiperOrigin-RevId: 283349646
    
  - Merge pull request #2607 from oyefremov:patch-1
    
    PiperOrigin-RevId: 283349621
    
  - Merge pull request #2583 from ChristophStrehle:master
    
    PiperOrigin-RevId: 282817206
    
  - Revert "remove MSVC workaround: wmain link error in the static library"
    
    This reverts commit 298a40f023e6813d2bf73847c3a38ceaf5e46320.
    
  - Revert "unify googletest and googlemock main functions"
    
    This reverts commit a909becdc599c46bcb57346b6123cb57cd07d15d.
    
  - Rename test case to test suite
  - Merge pull request #2604 from matepek:readme-update-with-opensource-proj
    
    PiperOrigin-RevId: 282620313
    
  - Merge pull request #2593 from kuzkry:remove-workaround_msvc-namespace-scope-from-nested-class
    
    PiperOrigin-RevId: 282593823
    
  - Merge pull request #2596 from kuzkry:remove-workaround_msvc-wmain-link-error
    
    PiperOrigin-RevId: 282589492
    
  - Merge pull request #2597 from kuzkry:remove-workaround_Nokia-Sybian-SafeMatcherCastImpl
    
    PiperOrigin-RevId: 282581402
    
  - Googletest export
    
    Wrap call to std::numeric_limits<>::max into round braces to appease MSVC.
    
    Closes #2589
    
    PiperOrigin-RevId: 282581361
    
  - Merge pull request #2591 from kuzkry:remove-workaround_g++-using-on-operator<<
    
    PiperOrigin-RevId: 282575040
    
  - Merge pull request #2588 from kuzkry:remove-workaround_g++-incorrect-comments
    
    PiperOrigin-RevId: 282568282
    
  - Googletest export
    
    Make generating goldens work with Python 3
    
    golden_file.write(output) fails with Python 3 with:
    TypeError: a bytes-like object is required, not 'str'
    PiperOrigin-RevId: 282316101
    
  - README.md: added Catch2 and Google Test Explorer
    
  - Fixed typo
  - Googletest export
    
    Fix typo in the predicate assertion table.
    
    PiperOrigin-RevId: 281973457
    
  - Merge pull request #2570 from xieyubo:1.10
    
    PiperOrigin-RevId: 281971090
    
  - Googletest export
    
    Use standard C++11 integer types in gtest-port.h.
    
    Remove testing::internal::{Int,Uint}{32,64} in favor of types
    guaranteed to be in <cstdint> since C++11.
    
    Tests for built-in integer type coverage are switched from
    {Int,Uint}64 to [unsigned] long long, which is guaranteed by
    C++11 to exist and be at least 64-bit wide.
    
    PiperOrigin-RevId: 281565263
    
  - unify googletest and googlemock main functions
    
  - remove MSVC workaround: wmain link error in the static library
    
  - remove Nokia's Symbian compiler workaround: SafeMatcherCastImpl
    
  - consistency fix for SafeMatcherCastImpl member functions
    
  - remove MSVC workaround: cease const dropping
    
  - remove MSVC workaround: accessing namespace scope from within nested classes
    
  - remove g++ 3.3 workaround: using on operator<<
    
  - Fix compile break for Microsoft Visual Studio 2017 v141
    
    This is a workaround, for those who have to compile with v141 build tools,
    for a bug in msvc that the compiler can't compile the WithArgsAction.
    
    see the following link for more details:
    https://developercommunityapi.westus.cloudapp.azure.com/content/problem/420339/googlemocks-withargs-doesnt-compile-with-permissiv.html
    
  - Merge pull request #2569 from bgianfo:master
    
    PiperOrigin-RevId: 281321427
    
  - Googletest export
    
    Add a breadcrumb about nullopt comparison near the Optional() matcher.
    
    Also add a note about how otherwise-spurious 'Eq()' may be needed in some cases. Without this, something like Field(&MyStruct::optional_field_without_equals_equals, absl::nullopt) doesn't work - it converts the nullopt to an optional<> of the non-equalable type, and fails to select the operator==(optional<>, nullopt_t) overload. The Eq() lets the type persist later into the match.
    
    PiperOrigin-RevId: 281305519
    
  - Googletest export
    
    Update stale comments to point to proper location.
    
    PiperOrigin-RevId: 281157036
    
  - Fix internal memory leak in Windows _Crt report.
    
    We use "MemoryIsNotDeallocated" to aovid internal expected leak reported
    in Windows _Crt report, like:
    
        {
        #ifdef _MSC_VER
        	MemoryIsNotDeallocated memory_is_not_deeallocated;
        #endif
    
        	static ThreadIdToThreadLocals* map = new
    	ThreadIdToThreadLocals();
    	return map;
        }
    
    But int the above code, only "new ThreadIdToThreadLocals()" is
    protected, if we invoke "insert()" function of the return value,
    the memory allocated in "insert()" will be reported to _Crt report
    also. This change try to fix this issue.
    
  - Fix FlatTuple compilation on older msvc.
    
    googletest 1.10.0 fails to compile on msvc version 19.00.23917
    with one compilation error:
    
    src\googletest\include\gtest\internal\gtest-internal.h(1188) : error C2039:
    'FlatTupleBase<testing::internal::FlatTuple<bool,bool>,testing::internal::IndexSequence<0,1> >':
    is not a member of 'testing::internal::FlatTuple<bool,bool>'
    
    This PR fixes the compilation error by explicitly specifying the full type that Indices is
    located in the base type.
    
  - Merge pull request #2521 from Sinclair-John:master
    
    PiperOrigin-RevId: 280666222
    
  - Merge pull request #2554 from kuzkry:update-gen_gtest_pred_impl
    
    PiperOrigin-RevId: 279734102
    
  - Merge pull request #2556 from ienorand:avoid-pkg-config-lpthread-cflag
    
    PiperOrigin-RevId: 279375858
    
  - Googletest export
    
    Correctly deal with stringification, and forbid empty arguments where they could slip thought, in the type parameterized test API.
    
    Note: even where empty args work, it's likely to result in technically invalid code by virtue of creating reserved identifiers:
    https://en.cppreference.com/w/cpp/language/identifiers
    PiperOrigin-RevId: 279330971
    
  - Googletest export
    
    Clone+exec death test allocates a single page of stack to run chdir + exec on.
    This is not enough when gtest is built with ASan and run on particular
    hardware.
    
    With ASan on x86_64, ExecDeathTestChildMain has frame size of 1728 bytes.
    
    Call to chdir() in ExecDeathTestChildMain ends up in
    _dl_runtime_resolve_xsavec, which attempts to save register state on the stack;
    according to cpuid(0xd) XSAVE register save area size is 2568 on my machine.
    
    This results in something like this in all death tests:
      Result: died but not with expected error.
      ...
      [  DEATH   ] AddressSanitizer:DEADLYSIGNAL
      [  DEATH   ] =================================================================
      [  DEATH   ] ==178637==ERROR: AddressSanitizer: stack-overflow on address ...
    
    PiperOrigin-RevId: 278709790
    
  - pkg-config: Remove pthread link flag from Cflags
    
    Remove the threads link library variable references from the pkg-config
    Cflags: field, removing -lpthread(s) from the compile flags.
    
    "-l*" linker flags should only be part of the Libs: section and should
    not be part of the Cflags: section in pkg-config files.
    
    This was first suggested in
    https://github.com/google/googletest/pull/2006 and further discussed in
    https://github.com/google/googletest/pull/2483 .
    
  - change incorrect comments
    
  - update gen_gtest_pred_impl.py
    
    After 7bd4a7f3 gtest_pred_impl_unittest.cc used to be newer than
    its template.
    
  - Fix Issue 2418