Update git submodules
* Update hardware/libhardware from branch 'master'
  to 9a2cf9a81852548e1af0247d4f8fe7e9080dd3fc
  - Merge "audio_alsaops: fix format conversion error handling bug"
  - audio_alsaops: fix format conversion error handling bug
    
    Returns a invalid format after fatal error,
    instead of "0", which equals to PCM_FORMAT_S16_LE or
    AUDIO_FORMAT_DEFAULT.
    
    Also fix below build error:
    hardware/libhardware/include/hardware/audio_alsaops.h:63:16:
    error: cannot initialize return object of type 'enum pcm_format' with an rvalue of type 'int'
            return 0;
    hardware/libhardware/include/hardware/audio_alsaops.h:97:16:
    error: cannot initialize return object of type 'audio_format_t' with an rvalue of type 'int'
            return 0;
    
    Signed-off-by: Jindong <jindong.yue@nxp.com>
    Change-Id: Iabf5ae106d9c371c00ad5236326c6f38d1a9f116
    
  - Merge "Add jni_headers to libinput_evdev" am: 93b6bed67a
    
    Change-Id: I27369268037d76af4a12d966fc5b98a6589efcfd
    
  - Merge "Add host_supported to libhardware_headers." am: 6df12d701d
    
    Change-Id: I7e0f4fc9d8f5178fa129a8ef2c655ce5a465cd0c
    
  - Merge "Add METADATA to libhardware: Apache2+BSD is NOTICE" am: 76ce69fa2e
    
    Change-Id: Ie683336a9c6d3c30097ffe586c3754e5eb05ae29
    
  - Merge "Set min_sdk_version to be part of mainline modules" am: 85d76c04ae
    
    Change-Id: Ib7f330fdeb4a8f7d31d0b862fd3dabd8d30826bf
    
  - DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp into stag-aosp-master
    
    Bug: 151763422
    Change-Id: I467045eb6fd9e04866c20618e6134e810593707a
    
  - Merge "audio remote submix: fix write blocked on input standby" am: 8705f278a3 am: e2ce03b586
    
    Change-Id: I001508c27fb44f469416298fb45a9a0c34e91d44
    
  - Merge "audio remote submix: fix write blocked on input standby" am: 8705f278a3
    
    Change-Id: I7b3edc2e7e6591af49d3ffb3938c7b2396ade48e
    
  - DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master am: cb9293b3de
    
    Change-Id: I639095e598396e4157ecf1f1a4de056da9a0ca6d
    
  - DO NOT MERGE - Empty merge qt-qpr1-dev-plus-aosp@6304901 into stag-aosp-master
    
    Bug: 151763422
    Change-Id: Iadd974705b931ff72e2e2222a092ed83d068ce59
    
  - Merge "Added identity credential key to keymaster tag set." am: 0f6a221b62 am: 353924555e
    
    Change-Id: I3d3dbcf2efe21edabb63d7e071f54920e993683a
    
  - Merge "Add Keymaster4.1 definitions." am: 09b2f93ab9 am: bf3974f323
    
    Change-Id: I6d588f874ea66cdfa372292aee1ee7d0809a1a3f
    
  - Add ROLLBACK_RESISTANCE definition to for KM4 am: ae001b8b33
    
    Change-Id: Id3bad86815fc5470d1891d8cc8dc5274cadf0ff9
    
  - Merge "DO NOT MERGE - Merge QQ1A.200205.002 into master" am: a8c23bc91e am: a2e1109653
    
    Change-Id: Ief2e8fd835612e700ddcc34a20069f52f4a788ab
    
  - DO NOT MERGE - Merge QQ1A.200205.002 into master am: ea78baf341 am: 594d100464
    
    Change-Id: I889ba9d170bd49daac8e018eeeb64c55eaff6b34
    
  - Add ROLLBACK_RESISTANCE definition to for KM4
    
    * Add ROLLBACK_RESISTANCE tag
    * Add ROLLBACK_RESISTANCE_UNAVAILABLE error code
    
    Test: m libkeymaster_messages
    Change-Id: Ib69a0c0f179f894b488da8608e6005e68450453a
    (cherry picked from commit df2f2301a30e236853a69d34ff4082f9e19ab7e2)
    
  - DO NOT MERGE - Merge qt-qpr1-dev-plus-aosp-without-vendor (6129114) into stage-aosp-master am: ead3ab68fe
    
    Change-Id: I104d6135b62c9367a6156f657370ad307fcdc92c
    
  - Merge "Audio HAL: Add API to attach an effect to a device" am: 2d0682b212 am: e16c3ebe00
    
    Change-Id: Idcd89be78d5c4470eb8958f5bf1e7f293f83580a
    
  - Merge "Audio effect HAL: Add create effect API with device ID" am: 4e018cf039 am: 51c5e608ff
    
    Change-Id: I43afddcf5dea43a26bbb24910237bfba6f87135c